services:
  strapi-poc:
    build: .
    image: strapi-poc:latest
    restart: unless-stopped
    environment:
      UPLOAD_GCS_BUCKET_NAME: sandbox-348610-strapi-upload
      DATABASE_HOST: strapi-poc-postgres
      DATABASE_NAME: strapi-poc
      DATABASE_USERNAME: strapi-poc
      APP_KEYS: VW/K6zUU9U//XrOLb3/mFA==,Xx6G9QbFdKgCweDpapRs2Q==,iKqjzF1TpDwTRhKxdRlKWQ==,P2WV6LkD2EcTVmuFsXO3xA==
      API_TOKEN_SALT: EKk7cI9PriLt0QgMrm0w6w==
      ADMIN_JWT_SECRET: wmISOcvjZPnHthf3XeLhEQ==
      DATABASE_PASSWORD: 5kMa9%nmdKcd6@
    ports:
      - 1337:1337
    depends_on:
      - strapi-poc-postgres

  strapi-poc-postgres:
    image: postgres:12.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi-poc
      POSTGRES_PASSWORD: 5kMa9%nmdKcd6@
      POSTGRES_DB: strapi-poc
